import { randomUUID } from 'node:crypto';
import type { FastifyBaseLogger } from 'fastify';
import { TC01A, type Alert, type LiveFrameHeader, type Mission, type Position, type RobotStatus, type SensorReading } from '@robodog/shared';
import type { Repositories } from '../db/repositories/index.js';
import type { Ingest } from '../services/ingest.js';
import type { Hub } from '../ws/hub.js';
import { renderSyntheticThermalJpeg } from './thermalFrame.js';

export const SIMULATION_MISSION_NAME = 'SIMULATION MISSION';
const SIM_PREFIX = '[SIMULATION] ';

export interface SimulatorOptions {
  sensorIntervalMs?: number;
  robotIntervalMs?: number;
  frameIntervalMs?: number;
  /** Deterministic randomness for tests. */
  random?: () => number;
}

/**
 * Generates clearly labelled synthetic data when ROBODOG_SIMULATION is enabled.
 * Every record carries source: 'SIMULATION'; alert messages are prefixed with "[SIMULATION] ";
 * live thermal frames are non-radiometric and declare source SIMULATION in their header.
 * The simulator is never constructed when the flag is off.
 */
export class Simulator {
  private timers: NodeJS.Timeout[] = [];
  private mission: Mission | null = null;
  private batteryPct = 100;
  private startedAt = Date.now();
  private readonly random: () => number;
  private readonly sensorIntervalMs: number;
  private readonly robotIntervalMs: number;
  private readonly frameIntervalMs: number;
  private frameCounter = 0;

  constructor(
    private readonly repos: Repositories,
    private readonly ingest: Ingest,
    private readonly hub: Hub,
    private readonly log: FastifyBaseLogger,
    options: SimulatorOptions = {},
  ) {
    this.random = options.random ?? Math.random;
    this.sensorIntervalMs = options.sensorIntervalMs ?? 1000;
    this.robotIntervalMs = options.robotIntervalMs ?? 5000;
    this.frameIntervalMs = options.frameIntervalMs ?? 250; // 4 fps
  }

  get missionId(): string | null {
    return this.mission?.id ?? null;
  }

  start(): void {
    if (this.timers.length) return;
    this.startedAt = Date.now();
    this.ensureMission();
    this.log.warn('SIMULATION MODE ENABLED: all generated data is labelled source=SIMULATION');
    const every = (ms: number, fn: () => void): void => {
      const t = setInterval(() => {
        try {
          fn();
        } catch (err) {
          this.log.error({ err }, 'simulation tick failed');
        }
      }, ms);
      t.unref();
      this.timers.push(t);
    };
    every(this.sensorIntervalMs, () => this.tickSensor());
    every(this.robotIntervalMs, () => this.tickRobot());
    every(this.frameIntervalMs, () => this.tickFrame());
    // Emit one of everything immediately so a fresh dashboard is not empty.
    this.tickSensor();
    this.tickRobot();
    this.tickFrame();
  }

  stop(): void {
    for (const t of this.timers) clearInterval(t);
    this.timers = [];
  }

  /** Reuse an active SIMULATION mission or create "SIMULATION MISSION". */
  private ensureMission(): void {
    const active = this.repos.missions.activeMission('SIMULATION');
    if (active) {
      this.mission = active;
      return;
    }
    this.mission = this.ingest.createMission({ name: SIMULATION_MISSION_NAME, source: 'SIMULATION', notes: 'Synthetic data generated by the server simulator. Not real.' }).mission;
  }

  private elapsedSeconds(): number {
    return (Date.now() - this.startedAt) / 1000;
  }

  /** Slow circle (radius 3 m, one lap per ~2 minutes) reported as low-confidence IMU dead reckoning. */
  private position(): Position {
    const t = this.elapsedSeconds();
    const angle = (t / 120) * 2 * Math.PI;
    return { x: Number((3 * Math.cos(angle)).toFixed(3)), y: Number((3 * Math.sin(angle)).toFixed(3)), z: 0, frame: 'IMU_DEAD_RECKONING', confidence: 0.2 };
  }

  private range(min: number, max: number, decimals = 1): number {
    return Number((min + this.random() * (max - min)).toFixed(decimals));
  }

  private tickSensor(): void {
    const gasAlert = this.random() < 0.03;
    const reading: SensorReading = {
      id: `sim_sensor_${randomUUID()}`,
      timestamp: new Date().toISOString(),
      missionId: this.missionId,
      source: 'SIMULATION',
      temperatureC: this.range(20, 35),
      humidityPct: this.range(40, 70),
      gasRaw: gasAlert ? Math.round(this.range(2200, 3000, 0)) : Math.round(this.range(1500, 2200, 0)),
      gasAlert,
      position: this.position(),
    };
    this.ingest.sensor(reading);
    if (gasAlert) {
      this.emitAlert({
        type: 'GAS_ALERT',
        severity: 'CRITICAL',
        message: `${SIM_PREFIX}Gas alert: simulated MQ raw value ${reading.gasRaw}`,
        metadata: { gasRaw: reading.gasRaw, temperatureC: reading.temperatureC, humidityPct: reading.humidityPct },
        position: reading.position,
      });
    } else if (this.random() < 0.02) {
      this.emitAlert({
        type: 'THERMAL_INTENSITY_HOTSPOT',
        severity: 'WARNING',
        message: `${SIM_PREFIX}Thermal intensity hotspot in synthetic frame (no temperature available)`,
        metadata: { thermalIntensity: this.range(0.85, 1, 2), radiometric: false },
        position: reading.position,
      });
    }
  }

  private emitAlert(partial: Pick<Alert, 'type' | 'severity' | 'message' | 'metadata' | 'position'>): void {
    const alert: Alert = {
      id: `sim_alert_${randomUUID()}`,
      timestamp: new Date().toISOString(),
      missionId: this.missionId,
      source: 'SIMULATION',
      thermalImageId: null,
      rgbImageId: null,
      acknowledged: false,
      ...partial,
    };
    this.ingest.alert(alert);
  }

  private tickRobot(): void {
    // ~1 % per minute at the default 5 s cadence.
    this.batteryPct = Math.max(0, this.batteryPct - (this.robotIntervalMs / 60_000));
    const status: RobotStatus = {
      timestamp: new Date().toISOString(),
      source: 'SIMULATION',
      phoneConnected: this.hub.phoneConnected,
      esp32Connected: false,
      thermalCameraConnected: false,
      robotConnected: false,
      batteryPct: Number(this.batteryPct.toFixed(1)),
      motorState: 'SIMULATED_WALK',
      legState: 'SIMULATED_TROT',
      imuAvailable: false,
      moving: true,
      slamStatus: null,
      gps: null,
      lidarAvailable: false,
      activeMissionId: this.missionId,
      extra: { simulation: true, position: this.position() },
    };
    this.ingest.robot(status);
  }

  private tickFrame(): void {
    // Only render when someone is watching; the cache still gets an initial frame.
    if (this.frameCounter > 0 && this.hub.webClientCount === 0) return;
    this.frameCounter++;
    const jpeg = renderSyntheticThermalJpeg({ phase: this.elapsedSeconds() });
    const header: LiveFrameHeader = {
      channel: 'thermal',
      timestamp: new Date().toISOString(),
      frameId: `sim_frame_${this.frameCounter}`,
      width: TC01A.THERMAL_WIDTH,
      height: TC01A.THERMAL_HEIGHT,
      palette: 'IRON',
      radiometric: false,
      centerTemperature: null,
      minTemperature: null,
      maxTemperature: null,
      source: 'SIMULATION',
    };
    this.hub.publishFrame(header, jpeg);
  }
}
